/*
 * weclapp api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: support@weclapp.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProductionOrderFastProductionBookingPostRequest {
    #[serde(rename = "quantity")]
    pub quantity: crate::models::custom_attribute_definition::AttributeType,
    #[serde(rename = "productionOrderNumber")]
    pub production_order_number: String,
}

impl ProductionOrderFastProductionBookingPostRequest {
    pub fn new(
        quantity: crate::models::custom_attribute_definition::AttributeType,
        production_order_number: String,
    ) -> ProductionOrderFastProductionBookingPostRequest {
        ProductionOrderFastProductionBookingPostRequest {
            quantity,
            production_order_number,
        }
    }
}
