/*
 * weclapp api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: support@weclapp.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PurchaseOrderIdIdCreateIncomingGoodsPostRequest {
    #[serde(
        rename = "additionalPurchaseOrderIds",
        skip_serializing_if = "Option::is_none"
    )]
    pub additional_purchase_order_ids: Option<Vec<String>>,
}

impl PurchaseOrderIdIdCreateIncomingGoodsPostRequest {
    pub fn new() -> PurchaseOrderIdIdCreateIncomingGoodsPostRequest {
        PurchaseOrderIdIdCreateIncomingGoodsPostRequest {
            additional_purchase_order_ids: None,
        }
    }
}
