/*
 * weclapp api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: support@weclapp.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TaxConfigureSalesTaxesPostRequest {
    #[serde(rename = "countryCode")]
    pub country_code: String,
    #[serde(rename = "personsThirdCountryFreeTax")]
    pub persons_third_country_free_tax: bool,
    #[serde(rename = "taxEuPersonsRecipientCountry")]
    pub tax_eu_persons_recipient_country: bool,
}

impl TaxConfigureSalesTaxesPostRequest {
    pub fn new(
        country_code: String,
        persons_third_country_free_tax: bool,
        tax_eu_persons_recipient_country: bool,
    ) -> TaxConfigureSalesTaxesPostRequest {
        TaxConfigureSalesTaxesPostRequest {
            country_code,
            persons_third_country_free_tax,
            tax_eu_persons_recipient_country,
        }
    }
}
