/*
 * weclapp api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: support@weclapp.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TaxResetSystemTaxesPostRequest {
    #[serde(rename = "countryCode")]
    pub country_code: String,
    #[serde(rename = "personsThirdCountryFreeTax")]
    pub persons_third_country_free_tax: bool,
    #[serde(rename = "initAllStores")]
    pub init_all_stores: bool,
    #[serde(rename = "taxRecipientCountry")]
    pub tax_recipient_country: bool,
}

impl TaxResetSystemTaxesPostRequest {
    pub fn new(
        country_code: String,
        persons_third_country_free_tax: bool,
        init_all_stores: bool,
        tax_recipient_country: bool,
    ) -> TaxResetSystemTaxesPostRequest {
        TaxResetSystemTaxesPostRequest {
            country_code,
            persons_third_country_free_tax,
            init_all_stores,
            tax_recipient_country,
        }
    }
}
