/*
 * weclapp api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: support@weclapp.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WarehouseStockMovementBookOutgoingMovementPostRequest {
    #[serde(rename = "articleId")]
    pub article_id: String,
    #[serde(rename = "quantity")]
    pub quantity: crate::models::custom_attribute_definition::AttributeType,
    #[serde(rename = "sourceWarehouseLevelId")]
    pub source_warehouse_level_id: String,
    #[serde(rename = "movementNote", skip_serializing_if = "Option::is_none")]
    pub movement_note: Option<String>,
    #[serde(rename = "batchNumber", skip_serializing_if = "Option::is_none")]
    pub batch_number: Option<String>,
    #[serde(rename = "serialNumbers", skip_serializing_if = "Option::is_none")]
    pub serial_numbers: Option<Vec<String>>,
    #[serde(rename = "customAttributes", skip_serializing_if = "Option::is_none")]
    pub custom_attributes: Option<Vec<crate::models::CustomAttribute>>,
}

impl WarehouseStockMovementBookOutgoingMovementPostRequest {
    pub fn new(
        article_id: String,
        quantity: crate::models::custom_attribute_definition::AttributeType,
        source_warehouse_level_id: String,
    ) -> WarehouseStockMovementBookOutgoingMovementPostRequest {
        WarehouseStockMovementBookOutgoingMovementPostRequest {
            article_id,
            quantity,
            source_warehouse_level_id,
            movement_note: None,
            batch_number: None,
            serial_numbers: None,
            custom_attributes: None,
        }
    }
}
