/*
 * weclapp api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: support@weclapp.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WarehouseStockMovementBookIncomingMovementPostRequest {
    #[serde(rename = "articleId")]
    pub article_id: String,
    #[serde(rename = "quantity")]
    pub quantity: crate::models::custom_attribute_definition::AttributeType,
    #[serde(
        rename = "articleValuationPrice",
        skip_serializing_if = "Option::is_none"
    )]
    pub article_valuation_price: Option<crate::models::custom_attribute_definition::AttributeType>,
    #[serde(rename = "targetWarehouseLevelId")]
    pub target_warehouse_level_id: String,
    #[serde(rename = "movementNote", skip_serializing_if = "Option::is_none")]
    pub movement_note: Option<String>,
    #[serde(rename = "batchNumber", skip_serializing_if = "Option::is_none")]
    pub batch_number: Option<String>,
    #[serde(
        rename = "batchNumberExpirationDate",
        skip_serializing_if = "Option::is_none"
    )]
    pub batch_number_expiration_date: Option<i32>,
    #[serde(rename = "serialNumbers", skip_serializing_if = "Option::is_none")]
    pub serial_numbers: Option<Vec<String>>,
    #[serde(rename = "customAttributes", skip_serializing_if = "Option::is_none")]
    pub custom_attributes: Option<Vec<crate::models::CustomAttribute>>,
}

impl WarehouseStockMovementBookIncomingMovementPostRequest {
    pub fn new(
        article_id: String,
        quantity: crate::models::custom_attribute_definition::AttributeType,
        target_warehouse_level_id: String,
    ) -> WarehouseStockMovementBookIncomingMovementPostRequest {
        WarehouseStockMovementBookIncomingMovementPostRequest {
            article_id,
            quantity,
            article_valuation_price: None,
            target_warehouse_level_id,
            movement_note: None,
            batch_number: None,
            batch_number_expiration_date: None,
            serial_numbers: None,
            custom_attributes: None,
        }
    }
}
