/*
 * weclapp api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: support@weclapp.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BankAccount {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "accountHolder", skip_serializing_if = "Option::is_none")]
    pub account_holder: Option<String>,
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    #[serde(rename = "accountNumber", skip_serializing_if = "Option::is_none")]
    pub account_number: Option<String>,
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "autoSync", skip_serializing_if = "Option::is_none")]
    pub auto_sync: Option<bool>,
    #[serde(
        rename = "automaticProcessing",
        skip_serializing_if = "Option::is_none"
    )]
    pub automatic_processing: Option<AutomaticProcessing>,
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<crate::models::custom_attribute_definition::AttributeType>,
    #[serde(rename = "bankCode", skip_serializing_if = "Option::is_none")]
    pub bank_code: Option<String>,
    #[serde(rename = "connectionFailure", skip_serializing_if = "Option::is_none")]
    pub connection_failure: Option<String>,
    #[serde(rename = "createdDate", skip_serializing_if = "Option::is_none")]
    pub created_date: Option<i32>,
    #[serde(rename = "creditInstitute", skip_serializing_if = "Option::is_none")]
    pub credit_institute: Option<String>,
    #[serde(
        rename = "creditInstituteCity",
        skip_serializing_if = "Option::is_none"
    )]
    pub credit_institute_city: Option<String>,
    #[serde(
        rename = "creditInstituteStreet",
        skip_serializing_if = "Option::is_none"
    )]
    pub credit_institute_street: Option<String>,
    #[serde(rename = "creditInstituteZip", skip_serializing_if = "Option::is_none")]
    pub credit_institute_zip: Option<String>,
    #[serde(rename = "creditLine", skip_serializing_if = "Option::is_none")]
    pub credit_line: Option<crate::models::custom_attribute_definition::AttributeType>,
    #[serde(rename = "currencyId", skip_serializing_if = "Option::is_none")]
    pub currency_id: Option<String>,
    #[serde(
        rename = "differentSepaCreditorIdentifier",
        skip_serializing_if = "Option::is_none"
    )]
    pub different_sepa_creditor_identifier: Option<String>,
    #[serde(
        rename = "enabledForElectronicPaymentTransactions",
        skip_serializing_if = "Option::is_none"
    )]
    pub enabled_for_electronic_payment_transactions: Option<bool>,
    #[serde(rename = "iban", skip_serializing_if = "Option::is_none")]
    pub iban: Option<String>,
    #[serde(
        rename = "incidentalCostsOfMonetaryTrafficAccountId",
        skip_serializing_if = "Option::is_none"
    )]
    pub incidental_costs_of_monetary_traffic_account_id: Option<String>,
    #[serde(
        rename = "incidentalCostsOfMonetaryTrafficTaxId",
        skip_serializing_if = "Option::is_none"
    )]
    pub incidental_costs_of_monetary_traffic_tax_id: Option<String>,
    #[serde(rename = "lastDownload", skip_serializing_if = "Option::is_none")]
    pub last_download: Option<i32>,
    #[serde(rename = "lastModifiedDate", skip_serializing_if = "Option::is_none")]
    pub last_modified_date: Option<i32>,
    #[serde(rename = "primary", skip_serializing_if = "Option::is_none")]
    pub primary: Option<bool>,
    #[serde(rename = "qrIban", skip_serializing_if = "Option::is_none")]
    pub qr_iban: Option<String>,
    #[serde(rename = "qrIdentifier", skip_serializing_if = "Option::is_none")]
    pub qr_identifier: Option<String>,
    #[serde(rename = "swiftBic", skip_serializing_if = "Option::is_none")]
    pub swift_bic: Option<String>,
}

impl BankAccount {
    pub fn new() -> BankAccount {
        BankAccount {
            id: None,
            version: None,
            account_holder: None,
            account_id: None,
            account_number: None,
            active: None,
            auto_sync: None,
            automatic_processing: None,
            balance: None,
            bank_code: None,
            connection_failure: None,
            created_date: None,
            credit_institute: None,
            credit_institute_city: None,
            credit_institute_street: None,
            credit_institute_zip: None,
            credit_line: None,
            currency_id: None,
            different_sepa_creditor_identifier: None,
            enabled_for_electronic_payment_transactions: None,
            iban: None,
            incidental_costs_of_monetary_traffic_account_id: None,
            incidental_costs_of_monetary_traffic_tax_id: None,
            last_download: None,
            last_modified_date: None,
            primary: None,
            qr_iban: None,
            qr_identifier: None,
            swift_bic: None,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AutomaticProcessing {
    #[serde(rename = "BOOK")]
    Book,
    #[serde(rename = "CLEAR")]
    Clear,
    #[serde(rename = "NONE")]
    None,
    #[serde(rename = "PROCESS")]
    Process,
}

impl Default for AutomaticProcessing {
    fn default() -> AutomaticProcessing {
        Self::Book
    }
}
