/*
 * weclapp api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: support@weclapp.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Period {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "createdDate", skip_serializing_if = "Option::is_none")]
    pub created_date: Option<i32>,
    #[serde(rename = "financialYearId")]
    pub financial_year_id: String,
    #[serde(rename = "lastModifiedDate", skip_serializing_if = "Option::is_none")]
    pub last_modified_date: Option<i32>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "open", skip_serializing_if = "Option::is_none")]
    pub open: Option<bool>,
    #[serde(rename = "periodNumber")]
    pub period_number: i32,
    #[serde(rename = "validFrom", skip_serializing_if = "Option::is_none")]
    pub valid_from: Option<i32>,
    #[serde(rename = "validTo", skip_serializing_if = "Option::is_none")]
    pub valid_to: Option<i32>,
}

impl Period {
    pub fn new(financial_year_id: String, name: String, period_number: i32) -> Period {
        Period {
            id: None,
            version: None,
            created_date: None,
            financial_year_id,
            last_modified_date: None,
            name,
            open: None,
            period_number,
            valid_from: None,
            valid_to: None,
        }
    }
}
