/*
 * weclapp api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: support@weclapp.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PriceCalculationParameter {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "createdDate", skip_serializing_if = "Option::is_none")]
    pub created_date: Option<i32>,
    #[serde(rename = "fixSurcharge", skip_serializing_if = "Option::is_none")]
    pub fix_surcharge: Option<crate::models::custom_attribute_definition::AttributeType>,
    #[serde(rename = "fromScale")]
    pub from_scale: crate::models::custom_attribute_definition::AttributeType,
    #[serde(rename = "lastModifiedDate", skip_serializing_if = "Option::is_none")]
    pub last_modified_date: Option<i32>,
    #[serde(rename = "lowerPurchasePriceBound")]
    pub lower_purchase_price_bound: crate::models::custom_attribute_definition::AttributeType,
    #[serde(rename = "margin", skip_serializing_if = "Option::is_none")]
    pub margin: Option<crate::models::custom_attribute_definition::AttributeType>,
    #[serde(rename = "percentSurcharge", skip_serializing_if = "Option::is_none")]
    pub percent_surcharge: Option<crate::models::custom_attribute_definition::AttributeType>,
    #[serde(rename = "profit", skip_serializing_if = "Option::is_none")]
    pub profit: Option<crate::models::custom_attribute_definition::AttributeType>,
    #[serde(rename = "salesChannel")]
    pub sales_channel: String,
}

impl PriceCalculationParameter {
    pub fn new(
        from_scale: crate::models::custom_attribute_definition::AttributeType,
        lower_purchase_price_bound: crate::models::custom_attribute_definition::AttributeType,
        sales_channel: String,
    ) -> PriceCalculationParameter {
        PriceCalculationParameter {
            id: None,
            version: None,
            created_date: None,
            fix_surcharge: None,
            from_scale,
            last_modified_date: None,
            lower_purchase_price_bound,
            margin: None,
            percent_surcharge: None,
            profit: None,
            sales_channel,
        }
    }
}
