/*
 * weclapp api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: support@weclapp.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProjectMembers {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "createdDate", skip_serializing_if = "Option::is_none")]
    pub created_date: Option<i32>,
    #[serde(rename = "hourlyCost", skip_serializing_if = "Option::is_none")]
    pub hourly_cost: Option<crate::models::custom_attribute_definition::AttributeType>,
    #[serde(rename = "lastModifiedDate", skip_serializing_if = "Option::is_none")]
    pub last_modified_date: Option<i32>,
    #[serde(rename = "teamRole", skip_serializing_if = "Option::is_none")]
    pub team_role: Option<TeamRole>,
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
}

impl ProjectMembers {
    pub fn new() -> ProjectMembers {
        ProjectMembers {
            id: None,
            version: None,
            created_date: None,
            hourly_cost: None,
            last_modified_date: None,
            team_role: None,
            user_id: None,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TeamRole {
    #[serde(rename = "MANAGER")]
    Manager,
    #[serde(rename = "USER")]
    User,
}

impl Default for TeamRole {
    fn default() -> TeamRole {
        Self::Manager
    }
}
