/*
 * weclapp api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: support@weclapp.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PurchaseOrderRequestOfferItemInformation {
    #[serde(rename = "offerItemId", skip_serializing_if = "Option::is_none")]
    pub offer_item_id: Option<i32>,
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<crate::models::custom_attribute_definition::AttributeType>,
    #[serde(rename = "salesOrderItemId", skip_serializing_if = "Option::is_none")]
    pub sales_order_item_id: Option<i32>,
    #[serde(rename = "updateInformation", skip_serializing_if = "Option::is_none")]
    pub update_information: Option<bool>,
}

impl PurchaseOrderRequestOfferItemInformation {
    pub fn new() -> PurchaseOrderRequestOfferItemInformation {
        PurchaseOrderRequestOfferItemInformation {
            offer_item_id: None,
            quantity: None,
            sales_order_item_id: None,
            update_information: None,
        }
    }
}
