/*
 * weclapp api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: support@weclapp.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PurchaseInvoiceItemRelationship {
    #[serde(
        rename = "purchaseInvoiceItemId",
        skip_serializing_if = "Option::is_none"
    )]
    pub purchase_invoice_item_id: Option<String>,
    #[serde(rename = "quantity")]
    pub quantity: crate::models::custom_attribute_definition::AttributeType,
    #[serde(rename = "shipmentItemId", skip_serializing_if = "Option::is_none")]
    pub shipment_item_id: Option<String>,
    #[serde(
        rename = "supplierOrderItemId",
        skip_serializing_if = "Option::is_none"
    )]
    pub supplier_order_item_id: Option<String>,
}

impl PurchaseInvoiceItemRelationship {
    pub fn new(
        quantity: crate::models::custom_attribute_definition::AttributeType,
    ) -> PurchaseInvoiceItemRelationship {
        PurchaseInvoiceItemRelationship {
            purchase_invoice_item_id: None,
            quantity,
            shipment_item_id: None,
            supplier_order_item_id: None,
        }
    }
}
