/*
 * weclapp api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: support@weclapp.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PurchaseOrder {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "commercialLanguage", skip_serializing_if = "Option::is_none")]
    pub commercial_language: Option<String>,
    #[serde(rename = "commission", skip_serializing_if = "Option::is_none")]
    pub commission: Option<String>,
    #[serde(rename = "createdDate", skip_serializing_if = "Option::is_none")]
    pub created_date: Option<i32>,
    #[serde(
        rename = "currencyConversionDate",
        skip_serializing_if = "Option::is_none"
    )]
    pub currency_conversion_date: Option<i32>,
    #[serde(
        rename = "currencyConversionRate",
        skip_serializing_if = "Option::is_none"
    )]
    pub currency_conversion_rate: Option<crate::models::custom_attribute_definition::AttributeType>,
    #[serde(rename = "customAttributes", skip_serializing_if = "Option::is_none")]
    pub custom_attributes: Option<Vec<crate::models::CustomAttribute>>,
    #[serde(rename = "deliveryAddress", skip_serializing_if = "Option::is_none")]
    pub delivery_address: Option<Box<crate::models::RecordAddress>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(
        rename = "disableEmailTemplate",
        skip_serializing_if = "Option::is_none"
    )]
    pub disable_email_template: Option<bool>,
    #[serde(
        rename = "externalPurchaseOrderNumber",
        skip_serializing_if = "Option::is_none"
    )]
    pub external_purchase_order_number: Option<String>,
    #[serde(rename = "grossAmount", skip_serializing_if = "Option::is_none")]
    pub gross_amount: Option<crate::models::custom_attribute_definition::AttributeType>,
    #[serde(
        rename = "grossAmountInCompanyCurrency",
        skip_serializing_if = "Option::is_none"
    )]
    pub gross_amount_in_company_currency:
        Option<crate::models::custom_attribute_definition::AttributeType>,
    #[serde(rename = "headerDiscount", skip_serializing_if = "Option::is_none")]
    pub header_discount: Option<crate::models::custom_attribute_definition::AttributeType>,
    #[serde(rename = "headerSurcharge", skip_serializing_if = "Option::is_none")]
    pub header_surcharge: Option<crate::models::custom_attribute_definition::AttributeType>,
    #[serde(rename = "invoiceAddress", skip_serializing_if = "Option::is_none")]
    pub invoice_address: Option<Box<crate::models::RecordAddress>>,
    #[serde(rename = "lastModifiedDate", skip_serializing_if = "Option::is_none")]
    pub last_modified_date: Option<i32>,
    #[serde(rename = "netAmount", skip_serializing_if = "Option::is_none")]
    pub net_amount: Option<crate::models::custom_attribute_definition::AttributeType>,
    #[serde(
        rename = "netAmountInCompanyCurrency",
        skip_serializing_if = "Option::is_none"
    )]
    pub net_amount_in_company_currency:
        Option<crate::models::custom_attribute_definition::AttributeType>,
    #[serde(rename = "nonStandardTaxId", skip_serializing_if = "Option::is_none")]
    pub non_standard_tax_id: Option<String>,
    #[serde(rename = "nonStandardTaxName", skip_serializing_if = "Option::is_none")]
    pub non_standard_tax_name: Option<String>,
    #[serde(rename = "orderDate", skip_serializing_if = "Option::is_none")]
    pub order_date: Option<i32>,
    #[serde(
        rename = "packageTrackingNumber",
        skip_serializing_if = "Option::is_none"
    )]
    pub package_tracking_number: Option<String>,
    #[serde(rename = "packageTrackingUrl", skip_serializing_if = "Option::is_none")]
    pub package_tracking_url: Option<String>,
    #[serde(rename = "paymentMethodId", skip_serializing_if = "Option::is_none")]
    pub payment_method_id: Option<String>,
    #[serde(rename = "paymentMethodName", skip_serializing_if = "Option::is_none")]
    pub payment_method_name: Option<String>,
    #[serde(
        rename = "plannedDeliveryDate",
        skip_serializing_if = "Option::is_none"
    )]
    pub planned_delivery_date: Option<i32>,
    #[serde(rename = "purchaseOrderItems", skip_serializing_if = "Option::is_none")]
    pub purchase_order_items: Option<Vec<crate::models::PurchaseOrderItem>>,
    #[serde(
        rename = "purchaseOrderNumber",
        skip_serializing_if = "Option::is_none"
    )]
    pub purchase_order_number: Option<String>,
    #[serde(rename = "purchaseOrderType", skip_serializing_if = "Option::is_none")]
    pub purchase_order_type: Option<PurchaseOrderType>,
    #[serde(rename = "received", skip_serializing_if = "Option::is_none")]
    pub received: Option<bool>,
    #[serde(rename = "recordAddress", skip_serializing_if = "Option::is_none")]
    pub record_address: Option<Box<crate::models::RecordAddress>>,
    #[serde(rename = "recordComment", skip_serializing_if = "Option::is_none")]
    pub record_comment: Option<String>,
    #[serde(rename = "recordCurrencyId", skip_serializing_if = "Option::is_none")]
    pub record_currency_id: Option<String>,
    #[serde(rename = "recordCurrencyName", skip_serializing_if = "Option::is_none")]
    pub record_currency_name: Option<String>,
    #[serde(
        rename = "recordEmailAddresses",
        skip_serializing_if = "Option::is_none"
    )]
    pub record_email_addresses: Option<Box<crate::models::EmailAddresses>>,
    #[serde(rename = "recordFreeText", skip_serializing_if = "Option::is_none")]
    pub record_free_text: Option<String>,
    #[serde(rename = "recordOpening", skip_serializing_if = "Option::is_none")]
    pub record_opening: Option<String>,
    #[serde(rename = "responsibleUserId", skip_serializing_if = "Option::is_none")]
    pub responsible_user_id: Option<String>,
    #[serde(
        rename = "responsibleUserUsername",
        skip_serializing_if = "Option::is_none"
    )]
    pub responsible_user_username: Option<String>,
    #[serde(rename = "salesOrderId", skip_serializing_if = "Option::is_none")]
    pub sales_order_id: Option<String>,
    #[serde(rename = "salesOrderNumber", skip_serializing_if = "Option::is_none")]
    pub sales_order_number: Option<String>,
    #[serde(rename = "sentToRecipient", skip_serializing_if = "Option::is_none")]
    pub sent_to_recipient: Option<bool>,
    #[serde(rename = "servicePeriodFrom", skip_serializing_if = "Option::is_none")]
    pub service_period_from: Option<i32>,
    #[serde(rename = "servicePeriodTo", skip_serializing_if = "Option::is_none")]
    pub service_period_to: Option<i32>,
    #[serde(rename = "shipmentMethodId", skip_serializing_if = "Option::is_none")]
    pub shipment_method_id: Option<String>,
    #[serde(rename = "shipmentMethodName", skip_serializing_if = "Option::is_none")]
    pub shipment_method_name: Option<String>,
    #[serde(rename = "shippingCarrierId", skip_serializing_if = "Option::is_none")]
    pub shipping_carrier_id: Option<String>,
    #[serde(rename = "shippingCostItems", skip_serializing_if = "Option::is_none")]
    pub shipping_cost_items: Option<Vec<crate::models::PurchaseShippingCostItem>>,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "statusHistory", skip_serializing_if = "Option::is_none")]
    pub status_history: Option<Vec<crate::models::PurchaseOrderStatusHistory>>,
    #[serde(
        rename = "supplierHabitualExporterLetterOfIntentId",
        skip_serializing_if = "Option::is_none"
    )]
    pub supplier_habitual_exporter_letter_of_intent_id: Option<String>,
    #[serde(rename = "supplierId")]
    pub supplier_id: String,
    #[serde(rename = "supplierNumber", skip_serializing_if = "Option::is_none")]
    pub supplier_number: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "termOfPaymentId", skip_serializing_if = "Option::is_none")]
    pub term_of_payment_id: Option<String>,
    #[serde(rename = "termOfPaymentName", skip_serializing_if = "Option::is_none")]
    pub term_of_payment_name: Option<String>,
    #[serde(rename = "warehouseId", skip_serializing_if = "Option::is_none")]
    pub warehouse_id: Option<String>,
    #[serde(rename = "warehouseName", skip_serializing_if = "Option::is_none")]
    pub warehouse_name: Option<String>,
}

impl PurchaseOrder {
    pub fn new(status: Status, supplier_id: String) -> PurchaseOrder {
        PurchaseOrder {
            id: None,
            version: None,
            commercial_language: None,
            commission: None,
            created_date: None,
            currency_conversion_date: None,
            currency_conversion_rate: None,
            custom_attributes: None,
            delivery_address: None,
            description: None,
            disable_email_template: None,
            external_purchase_order_number: None,
            gross_amount: None,
            gross_amount_in_company_currency: None,
            header_discount: None,
            header_surcharge: None,
            invoice_address: None,
            last_modified_date: None,
            net_amount: None,
            net_amount_in_company_currency: None,
            non_standard_tax_id: None,
            non_standard_tax_name: None,
            order_date: None,
            package_tracking_number: None,
            package_tracking_url: None,
            payment_method_id: None,
            payment_method_name: None,
            planned_delivery_date: None,
            purchase_order_items: None,
            purchase_order_number: None,
            purchase_order_type: None,
            received: None,
            record_address: None,
            record_comment: None,
            record_currency_id: None,
            record_currency_name: None,
            record_email_addresses: None,
            record_free_text: None,
            record_opening: None,
            responsible_user_id: None,
            responsible_user_username: None,
            sales_order_id: None,
            sales_order_number: None,
            sent_to_recipient: None,
            service_period_from: None,
            service_period_to: None,
            shipment_method_id: None,
            shipment_method_name: None,
            shipping_carrier_id: None,
            shipping_cost_items: None,
            status,
            status_history: None,
            supplier_habitual_exporter_letter_of_intent_id: None,
            supplier_id,
            supplier_number: None,
            tags: None,
            term_of_payment_id: None,
            term_of_payment_name: None,
            warehouse_id: None,
            warehouse_name: None,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PurchaseOrderType {
    #[serde(rename = "BLANKET_PURCHASE_ORDER")]
    BlanketPurchaseOrder,
    #[serde(rename = "NORMAL")]
    Normal,
    #[serde(rename = "SALES_ORDER")]
    SalesOrder,
    #[serde(rename = "TRIANGULAR")]
    Triangular,
}

impl Default for PurchaseOrderType {
    fn default() -> PurchaseOrderType {
        Self::BlanketPurchaseOrder
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "CANCELLED")]
    Cancelled,
    #[serde(rename = "CLOSED")]
    Closed,
    #[serde(rename = "CONFIRMED")]
    Confirmed,
    #[serde(rename = "ORDER_DOCUMENTS_PRINTED")]
    OrderDocumentsPrinted,
    #[serde(rename = "ORDER_ENTRY_COMPLETED")]
    OrderEntryCompleted,
    #[serde(rename = "ORDER_ENTRY_IN_PROGRESS")]
    OrderEntryInProgress,
}

impl Default for Status {
    fn default() -> Status {
        Self::Cancelled
    }
}
