/*
 * weclapp api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: support@weclapp.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QuantityConversion {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "conversionQuantity")]
    pub conversion_quantity: crate::models::custom_attribute_definition::AttributeType,
    #[serde(rename = "createdDate", skip_serializing_if = "Option::is_none")]
    pub created_date: Option<i32>,
    #[serde(rename = "createdUserId", skip_serializing_if = "Option::is_none")]
    pub created_user_id: Option<String>,
    #[serde(rename = "lastEditedUserId", skip_serializing_if = "Option::is_none")]
    pub last_edited_user_id: Option<String>,
    #[serde(rename = "lastModifiedDate", skip_serializing_if = "Option::is_none")]
    pub last_modified_date: Option<i32>,
    #[serde(rename = "oppositeDirection", skip_serializing_if = "Option::is_none")]
    pub opposite_direction: Option<bool>,
    #[serde(rename = "unitId")]
    pub unit_id: String,
}

impl QuantityConversion {
    pub fn new(
        conversion_quantity: crate::models::custom_attribute_definition::AttributeType,
        unit_id: String,
    ) -> QuantityConversion {
        QuantityConversion {
            id: None,
            version: None,
            conversion_quantity,
            created_date: None,
            created_user_id: None,
            last_edited_user_id: None,
            last_modified_date: None,
            opposite_direction: None,
            unit_id,
        }
    }
}
