/*
 * weclapp api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: support@weclapp.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SalesStageHistory {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "createdDate", skip_serializing_if = "Option::is_none")]
    pub created_date: Option<i32>,
    #[serde(rename = "lastModifiedDate", skip_serializing_if = "Option::is_none")]
    pub last_modified_date: Option<i32>,
    #[serde(rename = "salesStageId", skip_serializing_if = "Option::is_none")]
    pub sales_stage_id: Option<String>,
    #[serde(rename = "salesStageName", skip_serializing_if = "Option::is_none")]
    pub sales_stage_name: Option<String>,
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
}

impl SalesStageHistory {
    pub fn new() -> SalesStageHistory {
        SalesStageHistory {
            id: None,
            version: None,
            created_date: None,
            last_modified_date: None,
            sales_stage_id: None,
            sales_stage_name: None,
            user_id: None,
        }
    }
}
